### ISSUE TITLE
In custom scene file not picking up the colors, help needed

### ISSUE THREAD

**Issue by nomizodiac** [tangrams/tangram-cardboard#1]
In this project vr_scene.yaml file is loading as scene file which is working fine. I am trying to load my own custom scene.yaml file that has vector tiles in GeoJson format. Map is drawn properly like roads, building, river etc but it is not picking up the colors. Everything is in black color. I tried to change colors but with no effect.
Same scene file is loading/rendering perfectly on web or tangram-play browser. In my custom file I can only change the color of base layer or top background color like this:

```
scene:
    background:
#        color: '#E8E0D8'
        color: '#F0EDE5'
#         color: '#8db7d5'
```

But colors for roads,rivers, buildings etc shown in black only. Any help?
